/*
 * This file is part of Biblioteca-Digital de Univalle.
 *
 * Biblioteca-Digital de Univalle is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Biblioteca-Digital de Univalle is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with Biblioteca-Digital de Univalle.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

/*
 * GUICAT_Informacion_Basica.java
 *
 * Created on 7/05/2011, 04:04:25 PM
 */
package biblioteca.gui.catalogacion;

import biblioteca.database2.beans.Documento;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;

/**
 *
 * @author alejandro
 */
public class Informacion_Basica extends javax.swing.JPanel {
    Documento documento;    
    /** Creates new form GUICAT_Informacion_Basica */
    public Informacion_Basica(Documento documento) {
        initComponents();
        this.documento=documento;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        Titulo_Principal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Titulo_Secundario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Descripcion = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        Idioma = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        Editorial = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Derechos_Autor = new javax.swing.JTextField();
        Estado = new javax.swing.JLabel();
        Siguiente = new javax.swing.JButton();
        Editar = new javax.swing.JButton();
        DiaComboBox = new javax.swing.JComboBox();
        MesComboBox = new javax.swing.JComboBox();
        AnoComboBox = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Titulo Principal: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = null;
        gridBagConstraints.insets = new java.awt.Insets(11, 12, 0, 0);
        add(jLabel1, gridBagConstraints);

        Titulo_Principal.setPreferredSize(new java.awt.Dimension(200, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 28;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 468;
        gridBagConstraints.anchor = null;
        gridBagConstraints.insets = new java.awt.Insets(6, 7, 0, 0);
        add(Titulo_Principal, gridBagConstraints);

        jLabel2.setText("Titulo Secundario: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = null;
        gridBagConstraints.insets = new java.awt.Insets(20, 12, 0, 0);
        add(jLabel2, gridBagConstraints);

        Titulo_Secundario.setPreferredSize(new java.awt.Dimension(200, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 28;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 468;
        gridBagConstraints.anchor = null;
        gridBagConstraints.insets = new java.awt.Insets(15, 7, 0, 0);
        add(Titulo_Secundario, gridBagConstraints);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/gui/resources/logo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = null;
        add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 24));
        jLabel4.setText("Información Basica");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 42;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 29;
        gridBagConstraints.anchor = null;
        gridBagConstraints.insets = new java.awt.Insets(0, 80, 0, 0);
        add(jLabel4, gridBagConstraints);

        jLabel5.setText("Descripción: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 0, 0);
        add(jLabel5, gridBagConstraints);

        Descripcion.setColumns(20);
        Descripcion.setRows(5);
        Descripcion.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane1.setViewportView(Descripcion);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 28;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 456;
        gridBagConstraints.ipady = 80;
        gridBagConstraints.anchor = null;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 7, 0, 0);
        add(jScrollPane1, gridBagConstraints);

        jLabel6.setText("Idioma:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = null;
        gridBagConstraints.insets = new java.awt.Insets(18, 8, 0, 0);
        add(jLabel6, gridBagConstraints);

        Idioma.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Español", "Inglés", "Francés", "Aleman", "Portugués", "Otro" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 25;
        gridBagConstraints.anchor = null;
        gridBagConstraints.insets = new java.awt.Insets(13, 9, 0, 0);
        add(Idioma, gridBagConstraints);

        jLabel7.setText("Editorial: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = null;
        gridBagConstraints.insets = new java.awt.Insets(17, 12, 0, 0);
        add(jLabel7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 28;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 468;
        gridBagConstraints.anchor = null;
        gridBagConstraints.insets = new java.awt.Insets(12, 7, 0, 0);
        add(Editorial, gridBagConstraints);

        jLabel8.setText("Fecha Publicación:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = null;
        gridBagConstraints.insets = new java.awt.Insets(19, 12, 0, 0);
        add(jLabel8, gridBagConstraints);

        jLabel9.setText("Derechos de Autor: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = null;
        gridBagConstraints.insets = new java.awt.Insets(23, 7, 0, 0);
        add(jLabel9, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 28;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 466;
        gridBagConstraints.anchor = null;
        gridBagConstraints.insets = new java.awt.Insets(18, 9, 0, 0);
        add(Derechos_Autor, gridBagConstraints);

        Estado.setFont(new java.awt.Font("Ubuntu", 0, 24));
        Estado.setForeground(new java.awt.Color(255, 0, 0));
        Estado.setText("[Sin Guardar]");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = null;
        gridBagConstraints.insets = new java.awt.Insets(24, 12, 0, 0);
        add(Estado, gridBagConstraints);

        Siguiente.setFont(new java.awt.Font("Ubuntu", 1, 15));
        Siguiente.setText("Siguiente Paso");
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 43;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = null;
        gridBagConstraints.insets = new java.awt.Insets(27, 63, 12, 0);
        add(Siguiente, gridBagConstraints);

        Editar.setText("Editar");
        Editar.setEnabled(false);
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 44;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = null;
        gridBagConstraints.insets = new java.awt.Insets(32, 23, 0, 0);
        add(Editar, gridBagConstraints);

        DiaComboBox.setFont(new java.awt.Font("Arial", 0, 11));
        DiaComboBox.setMaximumRowCount(31);
        DiaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 18;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.anchor = null;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 0, 0);
        add(DiaComboBox, gridBagConstraints);

        MesComboBox.setFont(new java.awt.Font("Arial", 0, 11));
        MesComboBox.setMaximumRowCount(12);
        MesComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 42;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.anchor = null;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 0, 0);
        add(MesComboBox, gridBagConstraints);

        AnoComboBox.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        AnoComboBox.setMaximumRowCount(60);
        AnoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 44;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.anchor = null;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 0, 0);
        add(AnoComboBox, gridBagConstraints);

        jLabel10.setText("Año: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 43;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = null;
        gridBagConstraints.insets = new java.awt.Insets(19, 72, 0, 0);
        add(jLabel10, gridBagConstraints);

        jLabel11.setText("Mes: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 22;
        gridBagConstraints.anchor = null;
        gridBagConstraints.insets = new java.awt.Insets(19, 12, 0, 0);
        add(jLabel11, gridBagConstraints);

        jLabel12.setText("Día:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = null;
        gridBagConstraints.insets = new java.awt.Insets(19, 25, 0, 0);
        add(jLabel12, gridBagConstraints);

        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = null;
        gridBagConstraints.insets = new java.awt.Insets(11, 1, 0, 0);
        add(jLabel13, gridBagConstraints);

        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = null;
        gridBagConstraints.insets = new java.awt.Insets(20, 1, 0, 0);
        add(jLabel14, gridBagConstraints);

        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = null;
        gridBagConstraints.insets = new java.awt.Insets(18, 1, 0, 0);
        add(jLabel15, gridBagConstraints);

        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = null;
        gridBagConstraints.insets = new java.awt.Insets(17, 1, 0, 0);
        add(jLabel16, gridBagConstraints);

        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.anchor = null;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        add(jLabel17, gridBagConstraints);

        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.anchor = null;
        gridBagConstraints.insets = new java.awt.Insets(23, 6, 0, 0);
        add(jLabel18, gridBagConstraints);

        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = null;
        gridBagConstraints.insets = new java.awt.Insets(19, 1, 0, 0);
        add(jLabel19, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        if(checkEmptyFields()){
            guardarDatos();
            JTabbedPane parent =(JTabbedPane) this.getParent();
            parent.setSelectedIndex(1);
        }
    }//GEN-LAST:event_SiguienteActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        biblioteca.gui.GUICatalogacion.Informacion_Basica_Guardada=false;
        Estado.setForeground(Color.red);
        Estado.setText("[Sin guardar]");
        enableFields(true);
    }//GEN-LAST:event_EditarActionPerformed

    private boolean checkEmptyFields(){
        if(Titulo_Principal.getText()==null || Titulo_Principal.getText().equals("")){
            JOptionPane.showMessageDialog(this, "El campo Titulo Principal no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(Titulo_Secundario.getText()==null || Titulo_Secundario.getText().equals("")){
            JOptionPane.showMessageDialog(this, "El campo Titulo Secundario no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(Descripcion.getText()==null || Descripcion.getText().equals("")){
            JOptionPane.showMessageDialog(this, "El campo Descripcion no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(Editorial.getText()==null || Editorial.getText().equals("")){
            JOptionPane.showMessageDialog(this, "El campo Editorial no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(Derechos_Autor.getText()==null || Derechos_Autor.getText().equals("")){
            JOptionPane.showMessageDialog(this, "El campo Derechos de Autor no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else return true;
    }
    
    private void guardarDatos(){
        documento.setTituloPrincipal(Titulo_Principal.getText());
        documento.setTituloSecundario(Titulo_Secundario.getText());
        documento.setDescripcion(Descripcion.getText());
        documento.setEditorial(Editorial.getText());
        String fechaPub= (String) AnoComboBox.getSelectedItem();
        fechaPub+=(String) MesComboBox.getSelectedItem();
        fechaPub+=(String) DiaComboBox.getSelectedItem();
        documento.setFechaPublicacion(fechaPub);
        documento.setDerechosAutor(Derechos_Autor.getText());
        System.out.println(Idioma.getItemAt(Idioma.getSelectedIndex()));
        documento.setIdioma((String)Idioma.getItemAt(Idioma.getSelectedIndex()));
        Estado.setForeground(Color.green);
        Estado.setText("[Guardado]");
        enableFields(false);
        biblioteca.gui.GUICatalogacion.Informacion_Basica_Guardada=true;
    }
    
    private void enableFields(boolean b){
        Titulo_Principal.setEditable(b);
        Titulo_Principal.setEnabled(b);
        Titulo_Secundario.setEditable(b);
        Titulo_Secundario.setEnabled(b);
        Descripcion.setEditable(b);
        Descripcion.setEnabled(b);
        Editorial.setEditable(b);
        Editorial.setEnabled(b);
        AnoComboBox.setEnabled(b);
        DiaComboBox.setEnabled(b);
        MesComboBox.setEnabled(b);
        Derechos_Autor.setEditable(b);
        Derechos_Autor.setEnabled(b);
        Idioma.setEnabled(b);
        Editar.setEnabled(!b);
    }
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox AnoComboBox;
    private javax.swing.JTextField Derechos_Autor;
    private javax.swing.JTextArea Descripcion;
    private javax.swing.JComboBox DiaComboBox;
    private javax.swing.JButton Editar;
    private javax.swing.JTextField Editorial;
    private javax.swing.JLabel Estado;
    private javax.swing.JComboBox Idioma;
    private javax.swing.JComboBox MesComboBox;
    private javax.swing.JButton Siguiente;
    private javax.swing.JTextField Titulo_Principal;
    private javax.swing.JTextField Titulo_Secundario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
