/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Selecc_Areas.java
 *
 * Created on 7/05/2011, 08:16:46 PM
 */
package biblioteca.gui.catalogacion;

/**
 *
 * @author alejandro
 */
public class Selecc_Areas extends javax.swing.JPanel {

    /** Creates new form Selecc_Areas */
    public Selecc_Areas() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
