/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUICAT_Informacion_Basica.java
 *
 * Created on 7/05/2011, 04:04:25 PM
 */
package biblioteca.gui.modificacion;

import biblioteca.database2.accesoDatos.DaoDocumento;
import biblioteca.database2.beans.Documento;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;

/**
 *
 * @author alejandro
 */
public class Informacion_Basica extends javax.swing.JPanel {
    Documento documento;    
    biblioteca.gui.GUIModificacionDocumento parent;
    /** Creates new form GUICAT_Informacion_Basica */
    public Informacion_Basica(Documento documento, biblioteca.gui.GUIModificacionDocumento parent) {
        initComponents();
        this.documento=documento;
        this.parent=parent;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Titulo_Principal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Titulo_Secundario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Descripcion = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        Idioma = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        Editorial = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Fecha_Publicacion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Derechos_Autor = new javax.swing.JTextField();
        Estado = new javax.swing.JLabel();
        Siguiente = new javax.swing.JButton();
        Editar = new javax.swing.JButton();
        Consultar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        id_Documento = new javax.swing.JTextField();

        jLabel1.setText("Titulo Principal: ");

        Titulo_Principal.setPreferredSize(new java.awt.Dimension(200, 28));

        jLabel2.setText("Titulo Secundario: ");

        Titulo_Secundario.setPreferredSize(new java.awt.Dimension(200, 28));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/gui/resources/logo.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 24));
        jLabel4.setText("Información Basica");

        jLabel5.setText("Descripción:");

        Descripcion.setColumns(20);
        Descripcion.setRows(5);
        Descripcion.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jScrollPane1.setViewportView(Descripcion);

        jLabel6.setText("Idioma:");

        Idioma.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Inglés", "Español", "Portuges", "Otro" }));

        jLabel7.setText("Editorial: ");

        jLabel8.setText("Fecha Publicación: ");

        Fecha_Publicacion.setText("YYYYMMDD");

        jLabel9.setText("Derechos de Autor: ");

        Estado.setFont(new java.awt.Font("Ubuntu", 0, 24));
        Estado.setForeground(new java.awt.Color(255, 0, 0));
        Estado.setText("[Sin Guardar]");

        Siguiente.setFont(new java.awt.Font("Ubuntu", 1, 15));
        Siguiente.setText("Siguiente Paso");
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });

        Editar.setText("Editar");
        Editar.setEnabled(false);
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });

        Consultar.setText("Consultar Documento");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });

        jLabel10.setText("Identificador:");

        id_Documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_DocumentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jLabel4))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Estado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 320, Short.MAX_VALUE)
                .addComponent(Siguiente)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel6)
                        .addGap(102, 102, 102)
                        .addComponent(Idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Editar)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(id_Documento, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Consultar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Titulo_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(11, 11, 11)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(26, 26, 26)
                                            .addComponent(jLabel5)
                                            .addGap(24, 24, 24))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18))))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Derechos_Autor, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE))
                            .addComponent(Fecha_Publicacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                            .addComponent(Editorial, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Titulo_Secundario, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)))))
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(25, 25, 25)
                .addComponent(Editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Consultar)
                    .addComponent(id_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Titulo_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Titulo_Secundario, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Editorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fecha_Publicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Derechos_Autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel6))
                    .addComponent(Idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Siguiente)
                    .addComponent(Estado))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        if(checkEmptyFields()){
            guardarDatos();
            JTabbedPane panelParent =(JTabbedPane) this.getParent();
            panelParent.setSelectedIndex(1);
        }
    }//GEN-LAST:event_SiguienteActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed
        biblioteca.gui.GUIModificacionDocumento.Informacion_Basica_Guardada=false;
        enableFields(true);
    }//GEN-LAST:event_EditarActionPerformed

    private void id_DocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_DocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_DocumentoActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
         documento=new DaoDocumento().consultarDocumento(id_Documento.getText());
         if(!documento.getID_documento().equalsIgnoreCase("")){
             id_Documento.setEnabled(false);
             Titulo_Principal.setText(documento.getTituloPrincipal());
        Titulo_Secundario.setText(documento.getTituloSecundario());
        
        Descripcion.setText(documento.getTituloPrincipal());
       
        Editorial.setText(documento.getEditorial());
        
        Fecha_Publicacion.setText(documento.getFechaPublicacion());
        Derechos_Autor.setText(documento.getDerechosAutor());
        Idioma.setSelectedItem(documento.getIdioma());
        
        biblioteca.gui.GUIModificacionDocumento.documento=this.documento;
        parent.documentoAbierto();
         }
         else{
            JOptionPane.showMessageDialog(this, "El documento no existe, por favor ingrese ", "Error", JOptionPane.ERROR_MESSAGE);   
         }
    }//GEN-LAST:event_ConsultarActionPerformed

    private boolean checkEmptyFields(){
        if(Titulo_Principal.getText()==null || Titulo_Principal.getText().equals("")){
            JOptionPane.showMessageDialog(this, "El campo Titulo Principal no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(Titulo_Secundario.getText()==null || Titulo_Secundario.getText().equals("")){
            JOptionPane.showMessageDialog(this, "El campo Titulo Secundario no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(Descripcion.getText()==null || Descripcion.getText().equals("")){
            JOptionPane.showMessageDialog(this, "El campo Descripcion no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(Editorial.getText()==null || Editorial.getText().equals("")){
            JOptionPane.showMessageDialog(this, "El campo Editorial no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(Fecha_Publicacion.getText()==null || Fecha_Publicacion.getText().equals("") || Fecha_Publicacion.getText().equals("YYYYMMDD")){
            JOptionPane.showMessageDialog(this, "El campo Fecha Publicacion no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(Derechos_Autor.getText()==null || Derechos_Autor.getText().equals("")){
            JOptionPane.showMessageDialog(this, "El campo Derechos de Autor no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else return true;
    }
    
    private void guardarDatos(){
        documento.setTituloPrincipal(Titulo_Principal.getText());
        documento.setTituloSecundario(Titulo_Secundario.getText());
        documento.setDescripcion(Descripcion.getText());
        documento.setEditorial(Editorial.getText());
        documento.setFechaPublicacion(Fecha_Publicacion.getText());
        documento.setDerechosAutor(Derechos_Autor.getText());
        System.out.println(Idioma.getItemAt(Idioma.getSelectedIndex()));
        documento.setIdioma((String)Idioma.getItemAt(Idioma.getSelectedIndex()));
        Estado.setForeground(Color.green);
        Estado.setText("[Guardado]");
        enableFields(false);
        biblioteca.gui.GUIModificacionDocumento.Informacion_Basica_Guardada=true;
    }
    
    private void enableFields(boolean b){
        Titulo_Principal.setEditable(b);
        Titulo_Principal.setEnabled(b);
        Titulo_Secundario.setEditable(b);
        Titulo_Secundario.setEnabled(b);
        Descripcion.setEditable(b);
        Descripcion.setEnabled(b);
        Editorial.setEditable(b);
        Editorial.setEnabled(b);
        Fecha_Publicacion.setEditable(b);
        Fecha_Publicacion.setEnabled(b);
        Derechos_Autor.setEditable(b);
        Derechos_Autor.setEnabled(b);
        Idioma.setEnabled(b);
        Editar.setEnabled(!b);
    }
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Consultar;
    private javax.swing.JTextField Derechos_Autor;
    private javax.swing.JTextArea Descripcion;
    private javax.swing.JButton Editar;
    private javax.swing.JTextField Editorial;
    private javax.swing.JLabel Estado;
    private javax.swing.JTextField Fecha_Publicacion;
    private javax.swing.JComboBox Idioma;
    private javax.swing.JButton Siguiente;
    private javax.swing.JTextField Titulo_Principal;
    private javax.swing.JTextField Titulo_Secundario;
    private javax.swing.JTextField id_Documento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
