/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUIAgregarTipoDocumento.java
 *
 * Created on 6/06/2011, 11:53:08 AM
 */
package biblioteca.gui;

import biblioteca.database2.controladores.ControladorTipoDocumento;
import javax.swing.JOptionPane;

/**
 * Esta GUI permite crear tipos de documento en la base de datos de la apliación, sin necesidad de
 * abrir la GUI de Catalogación o modificación de documento
 * 
 * <br> Es el mismo codigo que está en biblioteca.gui.catalogacion.Tipo_Documento, solo
 * adaptado para una interfaz aparte
 * 
 * @see biblioteca.gui.catalogacion.Tipo_Documento
 *
 * @author María Cristina Bustos Rodríguez
 * @author Alejandro Valdés Villada
 */
public class GUIAgregarTipoDocumento extends javax.swing.JFrame {
    private javax.swing.JFrame parent;
    /** Creates new form GUIAgregarTipoDocumento */
    public GUIAgregarTipoDocumento(javax.swing.JFrame parent) {
        initComponents();
        this.parent=parent;
        this.setLocationRelativeTo(parent);
        this.setResizable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        Tipo_Nombre = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tipo_Descripcion = new javax.swing.JTextArea();
        Agregar = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel16.setText("Nombre: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel4.add(jLabel16, gridBagConstraints);

        jLabel17.setText("Descripción: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel4.add(jLabel17, gridBagConstraints);

        jLabel26.setForeground(new java.awt.Color(255, 0, 0));
        jLabel26.setText("*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridheight = 2;
        jPanel4.add(jLabel26, gridBagConstraints);

        jLabel27.setForeground(new java.awt.Color(255, 0, 0));
        jLabel27.setText("*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        jPanel4.add(jLabel27, gridBagConstraints);

        LimitadorDejTextField Tipo_NombreL=new LimitadorDejTextField(20);
        Tipo_Nombre.setDocument(Tipo_NombreL);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 20);
        jPanel4.add(Tipo_Nombre, gridBagConstraints);

        Tipo_Descripcion.setColumns(20);
        Tipo_Descripcion.setFont(new java.awt.Font("Tahoma", 0, 11));
        Tipo_Descripcion.setRows(5);
        LimitadorDejTextField Tipo_DescripcionL=new LimitadorDejTextField(200);
        Tipo_Descripcion.setDocument(Tipo_DescripcionL);
        jScrollPane2.setViewportView(Tipo_Descripcion);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 300;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 20);
        jPanel4.add(jScrollPane2, gridBagConstraints);

        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 18;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 20, 5);
        jPanel4.add(Agregar, gridBagConstraints);

        jLabel28.setFont(new java.awt.Font("Ubuntu", 1, 24));
        jLabel28.setText("Agregar Tipo de Documento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 18;
        jPanel4.add(jLabel28, gridBagConstraints);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/gui/resources/logo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 20, 0);
        jPanel4.add(jLabel29, gridBagConstraints);

        jLabel48.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel48.setText("Biblioteca Digital");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel4.add(jLabel48, gridBagConstraints);

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Comprueba campos vacios en la interfaz y envia un mensaje de error
     * explicando cual es el error al usuario
     * @return boolean indicando si no hay campos vacios en la interfaz
     */
    private boolean checkEmptyFieldsTipo(){
        if(Tipo_Nombre.getText()==null || Tipo_Nombre.getText().equals("")){
            JOptionPane.showMessageDialog(this, "El campo Nombre no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else if(Tipo_Descripcion.getText()==null || Tipo_Descripcion.getText().equals("")){
            JOptionPane.showMessageDialog(this, "El campo Descripcion no puede estar vacio", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        else return true;
    }
    
    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        if(checkEmptyFieldsTipo()){
            if(new ControladorTipoDocumento().agregarTipoDocumento(Tipo_Nombre.getText().toLowerCase().replaceAll("[']", "`"), Tipo_Descripcion.getText().replaceAll("[']", "`"))!=-1){
                JOptionPane.showMessageDialog(this, Tipo_Nombre.getText()+" ha sido agregado", "Notificación", JOptionPane.INFORMATION_MESSAGE);
                Tipo_Nombre.setText("");
                Tipo_Descripcion.setText("");
            } else{
                JOptionPane.showMessageDialog(this, Tipo_Nombre.getText()+" ya existe en la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
}//GEN-LAST:event_AgregarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
        parent.setVisible(true);         
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JTextArea Tipo_Descripcion;
    private javax.swing.JTextField Tipo_Nombre;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
