/*
 * This file is part of Biblioteca-Digital de Univalle.
 *
 * Biblioteca-Digital de Univalle is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Biblioteca-Digital de Univalle is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with Biblioteca-Digital de Univalle.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

/*
 * GUIBusquedaAvanzada.java
 *
 * Created on 15/05/2011, 04:17:18 PM
 */

package biblioteca.gui;

import biblioteca.database2.beans.Area;
import biblioteca.database2.beans.Autor;
import biblioteca.database2.beans.TipoDocumento;
import biblioteca.database2.controladores.ControladorArea;
import biblioteca.database2.controladores.ControladorDocumento;
import biblioteca.database2.controladores.ControladorTipoDocumento;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cris
 */
public class GUIBusquedaAvanzada extends javax.swing.JFrame {
    biblioteca.gui.GUIBusqueda parent;
    ArrayList<Area> areasExistentes;
     ArrayList<String> resultados;
    /** Creates new form GUIBusquedaAvanzada */
    public GUIBusquedaAvanzada(biblioteca.gui.GUIBusqueda parent) {
        this.parent=parent;
        areasExistentes= new ControladorArea().consultarTodasLasAreas();
        initComponents();
        initComboBoxArea();
        initComboBoxTipoMaterial();
        this.setLocationRelativeTo(parent);
        this.setExtendedState(this.MAXIMIZED_BOTH);   
    }


     private void initComboBoxArea(){
        AreaComboBox.removeAllItems();
        
        if(areasExistentes!=null){
            for(int i=0;i<areasExistentes.size();i++){
                if(i==0) AreaComboBox.insertItemAt("Cualquiera", 0);
                else AreaComboBox.insertItemAt(areasExistentes.get(i).getNombre(), i);
            }
           
            AreaComboBox.setSelectedIndex(0);
        }
    }
     private void initComboBoxTipoMaterial(){
         TipoMaterialComboBox.removeAllItems();
         ArrayList<TipoDocumento> tipoMaterialexistentes=new ControladorTipoDocumento().consultarTodosLosTipoDocumento();
         if(tipoMaterialexistentes!=null){
            for(int i=0;i<tipoMaterialexistentes.size();i++){
                TipoMaterialComboBox.insertItemAt(tipoMaterialexistentes.get(i).getTipoDocumento(), i);
            }
           TipoMaterialComboBox.insertItemAt("Cualquiera", 0);
           TipoMaterialComboBox.setSelectedIndex(0);
         }
     }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Resultados = new javax.swing.JTable();
        Consultar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(300, 0), new java.awt.Dimension(300, 0), new java.awt.Dimension(300, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(300, 0), new java.awt.Dimension(300, 0), new java.awt.Dimension(300, 32767));
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        titlelabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        TituloLabel = new javax.swing.JLabel();
        AutorLabel = new javax.swing.JLabel();
        PalabraClaveLabel = new javax.swing.JLabel();
        TituloTextField = new javax.swing.JTextField();
        AutorTextField = new javax.swing.JTextField();
        PalabraClaveTextField = new javax.swing.JTextField();
        TituloComboBox = new javax.swing.JComboBox();
        AutorComboBox = new javax.swing.JComboBox();
        PalabraClaveComboBox = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        AreaLabel = new javax.swing.JLabel();
        AreaComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        TipoMaterialComboBox = new javax.swing.JComboBox();
        MaterialLabel = new javax.swing.JLabel();
        IdiomaComboBox = new javax.swing.JComboBox();
        FechaLabel = new javax.swing.JLabel();
        FechaComboBox = new javax.swing.JComboBox();
        EditorialLabel = new javax.swing.JLabel();
        EditorialTextField = new javax.swing.JTextField();
        BuscarButton = new javax.swing.JButton();
        CancelarButton = new javax.swing.JButton();

        jPanel6.setLayout(new java.awt.GridBagLayout());

        jScrollPane2.setMinimumSize(new java.awt.Dimension(800, 200));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(800, 200));
        jScrollPane2.setRequestFocusEnabled(false);

        Resultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResultadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Resultados);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 20);
        jPanel6.add(jScrollPane2, gridBagConstraints);

        Consultar.setText("Consultar Documento Seleccionado");
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 20, 20);
        jPanel6.add(Consultar, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 24));
        jLabel7.setText("Resultados de Busqueda");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 10, 10);
        jPanel6.add(jLabel7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel6.add(filler2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel6.add(filler3, gridBagConstraints);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Búsqueda Avanzada");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(300, 450));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/gui/resources/logo.png"))); // NOI18N

        titlelabel.setFont(new java.awt.Font("Arial", 1, 24));
        titlelabel.setText("Busqueda Avanzada");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 24));
        jLabel5.setText("Biblioteca Digital");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(titlelabel)
                        .addGap(280, 280, 280))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titlelabel)
                .addContainerGap())
        );

        TituloLabel.setFont(new java.awt.Font("Arial", 0, 12));
        TituloLabel.setText("Titulo:");

        AutorLabel.setFont(new java.awt.Font("Arial", 0, 12));
        AutorLabel.setText("Autor:");

        PalabraClaveLabel.setFont(new java.awt.Font("Arial", 0, 12));
        PalabraClaveLabel.setText("Palabra Clave:");

        TituloTextField.setFont(new java.awt.Font("Arial", 0, 12));

        AutorTextField.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        PalabraClaveTextField.setFont(new java.awt.Font("Arial", 0, 12));

        TituloComboBox.setFont(new java.awt.Font("Arial", 0, 12));
        TituloComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "con todas las palabras", "con la frase exacta", "con alguna de las palabras", "sin las palabras" }));
        TituloComboBox.setMaximumSize(new java.awt.Dimension(182, 27));

        AutorComboBox.setFont(new java.awt.Font("Arial", 0, 12));
        AutorComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "con todas las palabras", "con la frase exacta", "con alguna de las palabras", "sin las palabras" }));
        AutorComboBox.setMaximumSize(new java.awt.Dimension(182, 27));
        AutorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutorComboBoxActionPerformed(evt);
            }
        });

        PalabraClaveComboBox.setFont(new java.awt.Font("Arial", 0, 12));
        PalabraClaveComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "con todas las palabras", "con la frase exacta", "con alguna de las palabras", "sin las palabras" }));
        PalabraClaveComboBox.setMaximumSize(new java.awt.Dimension(182, 27));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TituloLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AutorLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PalabraClaveLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PalabraClaveTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                    .addComponent(AutorTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                    .addComponent(TituloTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TituloComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AutorComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PalabraClaveComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TituloLabel)
                    .addComponent(TituloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TituloComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AutorLabel)
                    .addComponent(AutorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AutorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PalabraClaveLabel)
                    .addComponent(PalabraClaveTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PalabraClaveComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        AreaLabel.setFont(new java.awt.Font("Arial", 0, 12));
        AreaLabel.setText("Area: ");

        AreaComboBox.setFont(new java.awt.Font("Arial", 0, 12));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel6.setText("Idioma:");

        TipoMaterialComboBox.setFont(new java.awt.Font("Arial", 0, 12));

        MaterialLabel.setFont(new java.awt.Font("Arial", 0, 12));
        MaterialLabel.setText("Tipo de Material: ");

        IdiomaComboBox.setFont(new java.awt.Font("Arial", 0, 12));
        IdiomaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cualquiera", "Español", "Inglés", "Francés", "Aleman", "Portugués" }));

        FechaLabel.setFont(new java.awt.Font("Arial", 0, 12));
        FechaLabel.setText("Fecha de Publicación: ");

        FechaComboBox.setFont(new java.awt.Font("Arial", 0, 12));
        FechaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cualquier Fecha", "En el ultimo mes", "Hace 6 meses", "Hace un año", "Hace 2 años", "Hace 5 años" }));

        EditorialLabel.setFont(new java.awt.Font("Arial", 0, 12));
        EditorialLabel.setText("Editorial: ");

        EditorialTextField.setFont(new java.awt.Font("Arial", 0, 12));

        BuscarButton.setText("Buscar");
        BuscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarButtonActionPerformed(evt);
            }
        });

        CancelarButton.setText("Cancelar");
        CancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(AreaLabel)
                                .addComponent(MaterialLabel)))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(FechaLabel)))
                    .addComponent(EditorialLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EditorialTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addComponent(AreaComboBox, 0, 430, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(TipoMaterialComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(IdiomaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(FechaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                        .addComponent(BuscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(CancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AreaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AreaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditorialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditorialLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoMaterialComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdiomaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaterialLabel)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FechaLabel)
                    .addComponent(FechaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelarButton))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarButtonActionPerformed
        String titulo=TituloTextField.getText();
        String autor=AutorTextField.getText();
        String pc=PalabraClaveTextField.getText();
        int tituloopcion=TituloComboBox.getSelectedIndex();
        int autoropcion=AutorComboBox.getSelectedIndex();
        int pcopcion=PalabraClaveComboBox.getSelectedIndex();
        String area=(String)AreaComboBox.getSelectedItem();
        String editorial=EditorialTextField.getText();
        String tipo_material=(String)TipoMaterialComboBox.getSelectedItem();
        String idioma=(String)IdiomaComboBox.getSelectedItem();
        int fecha=FechaComboBox.getSelectedIndex();
        
       
       
       ArrayList<String> Titulo=new ArrayList<String>();
       ArrayList<String> Autor=new ArrayList<String>();
       ArrayList<String> PalabraClave=new ArrayList<String>();
       if(tituloopcion==1) Titulo.add(titulo);
       else {
           StringTokenizer titulotokens = new StringTokenizer(titulo, " ");
           while(titulotokens.hasMoreTokens())  Titulo.add(titulotokens.nextToken());
           }
       if(autoropcion==1) Autor.add(autor);
       else {
           StringTokenizer autortokens = new StringTokenizer(autor, " ");
            while(autortokens.hasMoreTokens()) Autor.add(autortokens.nextToken());
           }
       if(pcopcion==1) PalabraClave.add(pc);
       else {
            StringTokenizer palabraclavetokens = new StringTokenizer(pc, " ");
            while(palabraclavetokens.hasMoreTokens()) PalabraClave.add(palabraclavetokens.nextToken());
           }
       
       if(!area.equals("Cualquiera")) area=areasExistentes.get(AreaComboBox.getSelectedIndex()).getID();
       
       /*ArrayList<String> resultados = new ControladorDocumento().consultaDocumentoAvanzada( Titulo, Autor,
             PalabraClave,  tituloopcion, autoropcion,  pcopcion, area,
            editorial, tipo_material, idioma, fecha);

       if(!resultados.isEmpty()){
                new GUIResultados(resultados, this).setVisible(true);
                this.setVisible(false);
            }

            else
                JOptionPane.showMessageDialog(this, "La busqueda no ha retornado resultados", "Erorr", JOptionPane.ERROR_MESSAGE);*/
       resultados =new ControladorDocumento().consultaDocumentoAvanzada( Titulo, Autor,
             PalabraClave,  tituloopcion, autoropcion,  pcopcion, area,
            editorial, tipo_material, idioma, fecha);
       if(!resultados.isEmpty()){
                NoEditableTableModel modelo =new NoEditableTableModel();
                modelo.addColumn("Titulo");
            modelo.addColumn("Autores");
            for(int i=0;i<(int) resultados.size()/2;i++){
                String[] row = new String[2];
                row[0] =resultados.get(i*2+1);
                String autores="";
                ArrayList<Autor> obtenerAutores = new ControladorDocumento().obtenerAutores(resultados.get(i*2));
                for(int j=0;j<obtenerAutores.size();j++){
                    autores+=obtenerAutores.get(j).getNombre()+" "+obtenerAutores.get(j).getApellido();
                    if(j!=(obtenerAutores.size()-1))
                        autores+=", ";
                }
                row[1]=autores;
                modelo.addRow(row);
            }
            Resultados.setModel(modelo);
            this.getContentPane().add(jPanel6, "Center");
            //this.getContentPane().invalidate();
            this.getContentPane().repaint();
            this.pack();
            this.setExtendedState(this.MAXIMIZED_BOTH);        
            }
          else
                JOptionPane.showMessageDialog(this, "La busqueda no ha retornado resultados", "Erorr", JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_BuscarButtonActionPerformed



    private void AutorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutorComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AutorComboBoxActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        parent.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void CancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarButtonActionPerformed
                parent.setVisible(true);
                        this.dispose();

    }//GEN-LAST:event_CancelarButtonActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        int numeroSelecc=Resultados.getSelectedRow();
        if(numeroSelecc==-1){
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fila", "Error", JOptionPane.ERROR_MESSAGE);
        } else{
            
            new biblioteca.gui.GUIInformacionDocumento(this, resultados.get(numeroSelecc*2)).setVisible(true);
        }
}//GEN-LAST:event_ConsultarActionPerformed

    private void ResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResultadosMouseClicked
        if(evt.getClickCount()==2){
            int numeroSelecc=Resultados.getSelectedRow();
            new biblioteca.gui.GUIInformacionDocumento(this, resultados.get(numeroSelecc*2)).setVisible(true);
        }
    }//GEN-LAST:event_ResultadosMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox AreaComboBox;
    private javax.swing.JLabel AreaLabel;
    private javax.swing.JComboBox AutorComboBox;
    private javax.swing.JLabel AutorLabel;
    private javax.swing.JTextField AutorTextField;
    private javax.swing.JButton BuscarButton;
    private javax.swing.JButton CancelarButton;
    private javax.swing.JButton Consultar;
    private javax.swing.JLabel EditorialLabel;
    private javax.swing.JTextField EditorialTextField;
    private javax.swing.JComboBox FechaComboBox;
    private javax.swing.JLabel FechaLabel;
    private javax.swing.JComboBox IdiomaComboBox;
    private javax.swing.JLabel MaterialLabel;
    private javax.swing.JComboBox PalabraClaveComboBox;
    private javax.swing.JLabel PalabraClaveLabel;
    private javax.swing.JTextField PalabraClaveTextField;
    private javax.swing.JTable Resultados;
    private javax.swing.JComboBox TipoMaterialComboBox;
    private javax.swing.JComboBox TituloComboBox;
    private javax.swing.JLabel TituloLabel;
    private javax.swing.JTextField TituloTextField;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel titlelabel;
    // End of variables declaration//GEN-END:variables

}
