/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUIModificarAreas.java
 *
 * Created on 9/05/2011, 09:44:59 PM
 */

package biblioteca.gui;

import biblioteca.database2.beans.Area;
import biblioteca.database2.controladores.ControladorArea;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author Cris
 */
public class GUIModificarAreas extends javax.swing.JFrame {

    String username;
    Vector<String> areasExistentes, areasSeleccionadas;
    ArrayList<Area> areasexistentesarray, areasSeleccionadasarray;
    ArrayList<Area> areasAgregadas, areasEliminadas;
    biblioteca.gui.GUIBusqueda parent;
   
   
    /** Creates new form GUIModificarAreas */
    public GUIModificarAreas(biblioteca.gui.GUIBusqueda parent) {
        username=biblioteca.Main.BibliotecaDigital.LOGGED_USER;
        this.parent=parent;
        areasAgregadas=new ArrayList<Area>();
        areasEliminadas=new ArrayList<Area>();
        initComponents();
        initListExistentes();
        initListSeleccionadas();
        this.setLocationRelativeTo(parent);
        this.setResizable(false);
    }
    

    private void initListExistentes(){
       areasExistentes=new Vector<String>();
       areasexistentesarray=new ControladorArea().consultarTodasLasAreas();
       areasexistentesarray.remove(0);
       if(areasexistentesarray!=null){
           
            for(int i=0;i<areasexistentesarray.size();i++){
                areasExistentes.add(i,areasexistentesarray.get(i).toString());
            }
            
        }
       
       jList1.setListData(areasExistentes);
       jList1.setSelectedIndex(-1);
    }

    private void initListSeleccionadas(){
       areasSeleccionadas=new Vector<String>();
       areasSeleccionadasarray=new ControladorArea().consultarAreasporUsuario(username);
         if(areasSeleccionadasarray!=null){

            for(int i=0;i<areasSeleccionadasarray.size();i++){
                areasSeleccionadas.add(i,areasSeleccionadasarray.get(i).toString());
                System.out.println(areasSeleccionadas.get(i));
            }

        }
       jList2.setListData(areasSeleccionadas);
       jList2.setSelectedIndex(-1);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        Cancelar = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        Agregar = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        Agregar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/gui/resources/logo.png"))); // NOI18N

        jLabel48.setFont(new java.awt.Font("Ubuntu", 1, 24));
        jLabel48.setText("Biblioteca Digital");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jLabel48)
                .addGap(27, 27, 27))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel48)
                    .addComponent(jLabel43))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        Cancelar.setText("Cancelar Operación");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Ubuntu", 0, 18));
        jLabel44.setText("Áreas Existentes: ");

        Agregar.setText("Agregar Área de Interes");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Ubuntu", 0, 18));
        jLabel45.setText("Áreas Agregadas: ");

        jLabel46.setFont(new java.awt.Font("Ubuntu", 1, 24));
        jLabel46.setText("Modificar Áreas de Interés");

        jScrollPane1.setViewportView(jList1);

        Agregar1.setText("Eliminar Área de Interes");
        Agregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar1ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jList2);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(236, Short.MAX_VALUE)
                .addComponent(jLabel46)
                .addGap(200, 200, 200))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel44)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Cancelar)
                                    .addGap(18, 18, 18))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel45)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Agregar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(Agregar1)
                                .addGap(20, 20, 20)))
                        .addContainerGap(44, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel46)
                .addGap(48, 48, 48)
                .addComponent(jLabel44)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel45))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Agregar1)
                        .addComponent(Agregar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Cancelar))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
            this.dispose();
             parent.setVisible(true);
}//GEN-LAST:event_CancelarActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
      if(jList1.getSelectedIndex()!=-1){
            if(!areasSeleccionadas.contains(areasExistentes.get(jList1.getSelectedIndex()))){
                areasSeleccionadas.add(areasExistentes.get(jList1.getSelectedIndex()));
                areasAgregadas.add(areasexistentesarray.get(jList1.getSelectedIndex()));
            }
        }
        refreshAreas();
}//GEN-LAST:event_AgregarActionPerformed



    private void Agregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar1ActionPerformed
       if(jList2.getSelectedIndex()!=-1){
              areasSeleccionadas.removeElementAt(jList2.getSelectedIndex());
              areasEliminadas.add(areasSeleccionadasarray.get(jList2.getSelectedIndex()));
            }

        refreshAreas();
    }//GEN-LAST:event_Agregar1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int i=new ControladorArea().agregarAreasporUsuario(username, areasAgregadas);
        int j=new ControladorArea().eliminarAreasporUsuario(username, areasEliminadas);
        if(i!=-1 && j!=-1){

            JOptionPane.showMessageDialog(this, "Areas modificadas con Exito", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            parent.setVisible(true);
        }
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
        parent.setVisible(true);
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Agregar1;
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void refreshAreas() {
        jList2.setListData(areasSeleccionadas);
    }

}
