/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUIStatistics.java
 *
 * Created on 25/05/2011, 11:09:10 PM
 */
package biblioteca.gui;

import biblioteca.database2.beans.Area;
import biblioteca.database2.beans.Autor;
import biblioteca.database2.beans.TipoDocumento;
import biblioteca.database2.controladores.ControladorArea;
import biblioteca.database2.controladores.ControladorAutor;
import biblioteca.database2.controladores.ControladorEstadisticas;
import biblioteca.database2.controladores.ControladorTipoDocumento;
import java.util.ArrayList;

/**
 *
 * @author alejandro
 */
public class GUIStatistics extends javax.swing.JFrame {
    private ArrayList<Area> areasExistentes;
    private ArrayList<Autor> autoresExistentes;
    private ArrayList<TipoDocumento> tdExistentes;
    javax.swing.JFrame parent;
    /** Creates new form GUIStatistics */
    public GUIStatistics(javax.swing.JFrame parent) {
        initComponents();
        initAreas();
        initAutores();
        initTipoDocumento();
        this.parent=parent;
    }
    
    private void initAreas() {
        AreasComboBoxPDC.removeAllItems();
        AreasComboBoxPDD.removeAllItems();
        areasExistentes= new ControladorArea().consultarTodasLasAreas();
        AreasComboBoxPDC.insertItemAt("Cualquiera", 0);
        AreasComboBoxPDD.insertItemAt("Cualquiera", 0);
        if(areasExistentes!=null){
            for(int i=0;i<areasExistentes.size();i++){
                AreasComboBoxPDC.insertItemAt(areasExistentes.get(i).toString(), i+1);
                AreasComboBoxPDD.insertItemAt(areasExistentes.get(i).toString(), i+1);
            }
        }
         AreasComboBoxPDC.setSelectedIndex(0);
         AreasComboBoxPDD.setSelectedIndex(0);
    }
    
  private void initAutores() {
        AutorComboBoxPDC.removeAllItems();
        AutorComboBoxPDD.removeAllItems();
        AutorComboBoxPDC.insertItemAt("Cualquiera", 0);
        AutorComboBoxPDD.insertItemAt("Cualquiera", 0);
        autoresExistentes = new ControladorAutor().obtenerTodosLosAutores();
        if(autoresExistentes!=null){
            for(int i=0;i<autoresExistentes.size();i++){
                AutorComboBoxPDC.insertItemAt(autoresExistentes.get(i).toString(), i+1);
                AutorComboBoxPDD.insertItemAt(autoresExistentes.get(i).toString(), i+1);
            }
        }
        AutorComboBoxPDC.setSelectedIndex(0);
        AutorComboBoxPDD.setSelectedIndex(0);
          
    }
  
  private void initTipoDocumento() {
        DocTipoComboBoxPDC.removeAllItems();
        DocTipoComboBoxPDD.removeAllItems();
        DocTipoComboBoxPDC.insertItemAt("Cualquiera", 0);
        DocTipoComboBoxPDD.insertItemAt("Cualquiera", 0);
        
        tdExistentes = new ControladorTipoDocumento().consultarTodosLosTipoDocumento();
        if(tdExistentes!=null){
            for(int i=0;i<tdExistentes.size();i++){
                DocTipoComboBoxPDC.insertItemAt(tdExistentes.get(i).getTipoDocumento(), i+1);
                DocTipoComboBoxPDD.insertItemAt(tdExistentes.get(i).getTipoDocumento(), i+1);
            }
        }
        DocTipoComboBoxPDC.setSelectedIndex(0);
        DocTipoComboBoxPDD.setSelectedIndex(0);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jCheckBox45 = new javax.swing.JCheckBox();
        jComboBox107 = new javax.swing.JComboBox();
        jComboBox106 = new javax.swing.JComboBox();
        jComboBox105 = new javax.swing.JComboBox();
        jComboBox104 = new javax.swing.JComboBox();
        jCheckBox44 = new javax.swing.JCheckBox();
        jCheckBox43 = new javax.swing.JCheckBox();
        jCheckBox42 = new javax.swing.JCheckBox();
        jCheckBox41 = new javax.swing.JCheckBox();
        jCheckBox40 = new javax.swing.JCheckBox();
        jCheckBox39 = new javax.swing.JCheckBox();
        jLabel76 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jComboBox103 = new javax.swing.JComboBox();
        jComboBox102 = new javax.swing.JComboBox();
        jLabel74 = new javax.swing.JLabel();
        jComboBox101 = new javax.swing.JComboBox();
        jComboBox94 = new javax.swing.JComboBox();
        jComboBox100 = new javax.swing.JComboBox();
        jComboBox95 = new javax.swing.JComboBox();
        jComboBox98 = new javax.swing.JComboBox();
        jComboBox96 = new javax.swing.JComboBox();
        jLabel72 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jComboBox93 = new javax.swing.JComboBox();
        AreasComboBoxPDD = new javax.swing.JComboBox();
        AutorComboBoxPDD = new javax.swing.JComboBox();
        DocTipoComboBoxPDD = new javax.swing.JComboBox();
        jTextField7 = new javax.swing.JTextField();
        jLabel77 = new javax.swing.JLabel();
        Reporte_Descargados = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Num_Doc1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Panel_Documentos_Catalogados1 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        jCheckBox31 = new javax.swing.JCheckBox();
        jComboBox76 = new javax.swing.JComboBox();
        jCheckBox32 = new javax.swing.JCheckBox();
        jCheckBox33 = new javax.swing.JCheckBox();
        jComboBox77 = new javax.swing.JComboBox();
        jCheckBox34 = new javax.swing.JCheckBox();
        jComboBox78 = new javax.swing.JComboBox();
        jCheckBox35 = new javax.swing.JCheckBox();
        jCheckBox36 = new javax.swing.JCheckBox();
        jLabel63 = new javax.swing.JLabel();
        jComboBox79 = new javax.swing.JComboBox();
        jComboBox80 = new javax.swing.JComboBox();
        jLabel64 = new javax.swing.JLabel();
        jComboBox81 = new javax.swing.JComboBox();
        jCheckBox37 = new javax.swing.JCheckBox();
        jLabel65 = new javax.swing.JLabel();
        jComboBox82 = new javax.swing.JComboBox();
        jComboBox83 = new javax.swing.JComboBox();
        jComboBox84 = new javax.swing.JComboBox();
        jComboBox87 = new javax.swing.JComboBox();
        jComboBox88 = new javax.swing.JComboBox();
        jComboBox89 = new javax.swing.JComboBox();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jComboBox90 = new javax.swing.JComboBox();
        jLabel68 = new javax.swing.JLabel();
        AreasComboBoxPDC = new javax.swing.JComboBox();
        jLabel69 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AutorComboBoxPDC = new javax.swing.JComboBox();
        DocTipoComboBoxPDC = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        Reporte_Consultados = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Num_Doc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/gui/resources/logo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 24));
        jLabel6.setText("Estadisticas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jPanel1.add(jLabel6, gridBagConstraints);

        jLabel78.setFont(new java.awt.Font("Ubuntu", 1, 11));
        jLabel78.setText("Estadisticas de Documentos Más Descargados: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        jPanel1.add(jLabel78, gridBagConstraints);

        buttonGroup1.add(jCheckBox45);
        jCheckBox45.setSelected(true);
        jCheckBox45.setText("Todas");
        jCheckBox45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox45ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel1.add(jCheckBox45, gridBagConstraints);

        jComboBox107.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo" }));
        jComboBox107.setPreferredSize(new java.awt.Dimension(56, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(jComboBox107, gridBagConstraints);

        jComboBox106.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBox106.setPreferredSize(new java.awt.Dimension(56, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(jComboBox106, gridBagConstraints);

        jComboBox105.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jComboBox105.setPreferredSize(new java.awt.Dimension(56, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(jComboBox105, gridBagConstraints);

        jComboBox104.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2011", "2010", "2009" }));
        jComboBox104.setPreferredSize(new java.awt.Dimension(56, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(jComboBox104, gridBagConstraints);

        buttonGroup1.add(jCheckBox44);
        jCheckBox44.setText("Por dia de la Semana:");
        jCheckBox44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox44ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        jPanel1.add(jCheckBox44, gridBagConstraints);

        buttonGroup1.add(jCheckBox43);
        jCheckBox43.setText("Por dia del Mes:");
        jCheckBox43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox43ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        jPanel1.add(jCheckBox43, gridBagConstraints);

        buttonGroup1.add(jCheckBox42);
        jCheckBox42.setText("Por Mes:");
        jCheckBox42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox42ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        jPanel1.add(jCheckBox42, gridBagConstraints);

        buttonGroup1.add(jCheckBox41);
        jCheckBox41.setText("Por Año:");
        jCheckBox41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox41ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        jPanel1.add(jCheckBox41, gridBagConstraints);

        jCheckBox40.setText("Por Franja Horaria:");
        jCheckBox40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox40ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 2;
        jPanel1.add(jCheckBox40, gridBagConstraints);

        buttonGroup1.add(jCheckBox39);
        jCheckBox39.setText("Intervalo de Tiempo:");
        jCheckBox39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox39ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 2;
        jPanel1.add(jCheckBox39, gridBagConstraints);

        jLabel76.setText("Desde:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        jPanel1.add(jLabel76, gridBagConstraints);

        jLabel75.setText("Hasta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        jPanel1.add(jLabel75, gridBagConstraints);

        jLabel73.setText("Desde:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        jPanel1.add(jLabel73, gridBagConstraints);

        jComboBox103.setMaximumRowCount(12);
        jComboBox103.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));
        jComboBox103.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 5);
        jPanel1.add(jComboBox103, gridBagConstraints);

        jComboBox102.setMaximumRowCount(12);
        jComboBox102.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));
        jComboBox102.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 5);
        jPanel1.add(jComboBox102, gridBagConstraints);

        jLabel74.setText("Hasta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        jPanel1.add(jLabel74, gridBagConstraints);

        jComboBox101.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBox101.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 5);
        jPanel1.add(jComboBox101, gridBagConstraints);

        jComboBox94.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBox94.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 5);
        jPanel1.add(jComboBox94, gridBagConstraints);

        jComboBox100.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jComboBox100.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 5);
        jPanel1.add(jComboBox100, gridBagConstraints);

        jComboBox95.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jComboBox95.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 5);
        jPanel1.add(jComboBox95, gridBagConstraints);

        jComboBox98.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2011", "2010", "2009" }));
        jComboBox98.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 5);
        jPanel1.add(jComboBox98, gridBagConstraints);

        jComboBox96.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2011", "2010", "2009" }));
        jComboBox96.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 5);
        jPanel1.add(jComboBox96, gridBagConstraints);

        jLabel72.setText("Por Tipo de Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 5);
        jPanel1.add(jLabel72, gridBagConstraints);

        jLabel71.setText("Por Áreas de Conocimiento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 5);
        jPanel1.add(jLabel71, gridBagConstraints);

        jLabel1.setText("Por Autor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 5);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Por Tipo de Documento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 5);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel70.setText("Por un Usuario Particular:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 5);
        jPanel1.add(jLabel70, gridBagConstraints);

        jComboBox93.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cualquiera", "Usuario Normal", "Usuario Catalogador" }));
        jComboBox93.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 5);
        jPanel1.add(jComboBox93, gridBagConstraints);

        AreasComboBoxPDD.setPreferredSize(new java.awt.Dimension(180, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 5);
        jPanel1.add(AreasComboBoxPDD, gridBagConstraints);

        AutorComboBoxPDD.setPreferredSize(new java.awt.Dimension(180, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 5);
        jPanel1.add(AutorComboBoxPDD, gridBagConstraints);

        DocTipoComboBoxPDD.setPreferredSize(new java.awt.Dimension(180, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 5);
        jPanel1.add(DocTipoComboBoxPDD, gridBagConstraints);

        jTextField7.setEditable(false);
        jTextField7.setForeground(new java.awt.Color(102, 102, 102));
        jTextField7.setText("Digite su Username");
        jTextField7.setPreferredSize(new java.awt.Dimension(110, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 5);
        jPanel1.add(jTextField7, gridBagConstraints);

        jLabel77.setText("Fecha de Descarga:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        jPanel1.add(jLabel77, gridBagConstraints);

        Reporte_Descargados.setText("Generar Reporte");
        Reporte_Descargados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reporte_DescargadosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        jPanel1.add(Reporte_Descargados, gridBagConstraints);

        jLabel10.setText("N° de documentos: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel1.add(jLabel10, gridBagConstraints);

        Num_Doc1.setText("10");
        Num_Doc1.setPreferredSize(new java.awt.Dimension(60, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(Num_Doc1, gridBagConstraints);

        jTabbedPane1.addTab("Documentos más descargados", jPanel1);
        jTabbedPane1.addTab("tab2", jPanel2);

        Panel_Documentos_Catalogados1.setLayout(new java.awt.GridBagLayout());

        jLabel61.setText("Fecha de Consulta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        Panel_Documentos_Catalogados1.add(jLabel61, gridBagConstraints);

        buttonGroup2.add(jCheckBox31);
        jCheckBox31.setText("Cualquiera");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        Panel_Documentos_Catalogados1.add(jCheckBox31, gridBagConstraints);

        jComboBox76.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo" }));
        jComboBox76.setPreferredSize(new java.awt.Dimension(56, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        Panel_Documentos_Catalogados1.add(jComboBox76, gridBagConstraints);

        buttonGroup2.add(jCheckBox32);
        jCheckBox32.setText("Por dia de la Semana:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        Panel_Documentos_Catalogados1.add(jCheckBox32, gridBagConstraints);

        buttonGroup2.add(jCheckBox33);
        jCheckBox33.setText("Por dia del Mes");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        Panel_Documentos_Catalogados1.add(jCheckBox33, gridBagConstraints);

        jComboBox77.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBox77.setPreferredSize(new java.awt.Dimension(56, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        Panel_Documentos_Catalogados1.add(jComboBox77, gridBagConstraints);

        buttonGroup2.add(jCheckBox34);
        jCheckBox34.setText("Por Mes:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        Panel_Documentos_Catalogados1.add(jCheckBox34, gridBagConstraints);

        jComboBox78.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jComboBox78.setPreferredSize(new java.awt.Dimension(56, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        Panel_Documentos_Catalogados1.add(jComboBox78, gridBagConstraints);

        buttonGroup2.add(jCheckBox35);
        jCheckBox35.setText("Por Año:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        Panel_Documentos_Catalogados1.add(jCheckBox35, gridBagConstraints);

        jCheckBox36.setText("Por Franja Horaria:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        Panel_Documentos_Catalogados1.add(jCheckBox36, gridBagConstraints);

        jLabel63.setText("Desde:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        Panel_Documentos_Catalogados1.add(jLabel63, gridBagConstraints);

        jComboBox79.setMaximumRowCount(12);
        jComboBox79.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));
        jComboBox79.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 5);
        Panel_Documentos_Catalogados1.add(jComboBox79, gridBagConstraints);

        jComboBox80.setMaximumRowCount(12);
        jComboBox80.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00:00", "01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));
        jComboBox80.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 5);
        Panel_Documentos_Catalogados1.add(jComboBox80, gridBagConstraints);

        jLabel64.setText("Hasta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        Panel_Documentos_Catalogados1.add(jLabel64, gridBagConstraints);

        jComboBox81.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2011", "2010", "2009" }));
        jComboBox81.setPreferredSize(new java.awt.Dimension(56, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        Panel_Documentos_Catalogados1.add(jComboBox81, gridBagConstraints);

        buttonGroup2.add(jCheckBox37);
        jCheckBox37.setText("Intervalo de Tiempo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        Panel_Documentos_Catalogados1.add(jCheckBox37, gridBagConstraints);

        jLabel65.setText("Desde:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        Panel_Documentos_Catalogados1.add(jLabel65, gridBagConstraints);

        jComboBox82.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBox82.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 5);
        Panel_Documentos_Catalogados1.add(jComboBox82, gridBagConstraints);

        jComboBox83.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jComboBox83.setPreferredSize(new java.awt.Dimension(70, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 5);
        Panel_Documentos_Catalogados1.add(jComboBox83, gridBagConstraints);

        jComboBox84.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2011", "2010", "2009" }));
        jComboBox84.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 5);
        Panel_Documentos_Catalogados1.add(jComboBox84, gridBagConstraints);

        jComboBox87.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2011", "2010", "2009" }));
        jComboBox87.setPreferredSize(new java.awt.Dimension(50, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 5);
        Panel_Documentos_Catalogados1.add(jComboBox87, gridBagConstraints);

        jComboBox88.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jComboBox88.setPreferredSize(new java.awt.Dimension(70, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 5);
        Panel_Documentos_Catalogados1.add(jComboBox88, gridBagConstraints);

        jComboBox89.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBox89.setPreferredSize(new java.awt.Dimension(60, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 5);
        Panel_Documentos_Catalogados1.add(jComboBox89, gridBagConstraints);

        jLabel66.setText("Hasta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        Panel_Documentos_Catalogados1.add(jLabel66, gridBagConstraints);

        jLabel67.setText("Por Tipo de Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 5);
        Panel_Documentos_Catalogados1.add(jLabel67, gridBagConstraints);

        jComboBox90.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cualquiera", "Usuario Normal", "Usuario Catalogador" }));
        jComboBox90.setPreferredSize(new java.awt.Dimension(100, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 5);
        Panel_Documentos_Catalogados1.add(jComboBox90, gridBagConstraints);

        jLabel68.setText("Por Áreas de Conocimiento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 5);
        Panel_Documentos_Catalogados1.add(jLabel68, gridBagConstraints);

        AreasComboBoxPDC.setPreferredSize(new java.awt.Dimension(180, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 5);
        Panel_Documentos_Catalogados1.add(AreasComboBoxPDC, gridBagConstraints);

        jLabel69.setText("Por un Usuario Particular:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 5);
        Panel_Documentos_Catalogados1.add(jLabel69, gridBagConstraints);

        jTextField6.setEditable(false);
        jTextField6.setForeground(new java.awt.Color(102, 102, 102));
        jTextField6.setText("Digite su Username");
        jTextField6.setPreferredSize(new java.awt.Dimension(110, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 5);
        Panel_Documentos_Catalogados1.add(jTextField6, gridBagConstraints);

        jLabel62.setFont(new java.awt.Font("Ubuntu", 1, 11));
        jLabel62.setText("Reporte de Documentos Consultados: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        Panel_Documentos_Catalogados1.add(jLabel62, gridBagConstraints);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biblioteca/gui/resources/logo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        Panel_Documentos_Catalogados1.add(jLabel7, gridBagConstraints);

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 24));
        jLabel8.setText("Reportes y Estadisticas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        Panel_Documentos_Catalogados1.add(jLabel8, gridBagConstraints);

        jLabel3.setText("Por Autor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 5);
        Panel_Documentos_Catalogados1.add(jLabel3, gridBagConstraints);

        AutorComboBoxPDC.setPreferredSize(new java.awt.Dimension(180, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 5);
        Panel_Documentos_Catalogados1.add(AutorComboBoxPDC, gridBagConstraints);

        DocTipoComboBoxPDC.setPreferredSize(new java.awt.Dimension(180, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 5);
        Panel_Documentos_Catalogados1.add(DocTipoComboBoxPDC, gridBagConstraints);

        jLabel4.setText("Por Tipo de Documento:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 10, 5);
        Panel_Documentos_Catalogados1.add(jLabel4, gridBagConstraints);

        Reporte_Consultados.setText("Generar Reporte");
        Reporte_Consultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reporte_ConsultadosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 10);
        Panel_Documentos_Catalogados1.add(Reporte_Consultados, gridBagConstraints);

        jLabel9.setText("N° de documentos: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        Panel_Documentos_Catalogados1.add(jLabel9, gridBagConstraints);

        Num_Doc.setText("10");
        Num_Doc.setPreferredSize(new java.awt.Dimension(60, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        Panel_Documentos_Catalogados1.add(Num_Doc, gridBagConstraints);

        jTabbedPane1.addTab("Documentos más consultados", Panel_Documentos_Catalogados1);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox45ActionPerformed
        jCheckBox40.setSelected(false);
    }//GEN-LAST:event_jCheckBox45ActionPerformed

    private void jCheckBox44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox44ActionPerformed
        jCheckBox40.setSelected(false);
    }//GEN-LAST:event_jCheckBox44ActionPerformed

    private void jCheckBox43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox43ActionPerformed
        jCheckBox40.setSelected(false);
    }//GEN-LAST:event_jCheckBox43ActionPerformed

    private void jCheckBox42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox42ActionPerformed
        jCheckBox40.setSelected(false);
    }//GEN-LAST:event_jCheckBox42ActionPerformed

    private void jCheckBox41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox41ActionPerformed
        jCheckBox40.setSelected(false);
    }//GEN-LAST:event_jCheckBox41ActionPerformed

    private void jCheckBox39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox39ActionPerformed
        jCheckBox40.setSelected(false);
    }//GEN-LAST:event_jCheckBox39ActionPerformed

    private void jCheckBox40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox40ActionPerformed
        jCheckBox45.setSelected(false);
        jCheckBox44.setSelected(false);
        jCheckBox43.setSelected(false);
        jCheckBox42.setSelected(false);
        jCheckBox41.setSelected(false);
        jCheckBox39.setSelected(false);
    }//GEN-LAST:event_jCheckBox40ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
        parent.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void Reporte_DescargadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reporte_DescargadosActionPerformed
        String dow = null, dom = null, month = null, year = null, tipo_usuario = null;
        String[] franja = null, desde = null, Hasta = null;
        String area = null, autor=null, doc_tipo=null, usuario=null;
      
          if(jCheckBox44.isSelected()) dow=jComboBox107.getSelectedIndex()+"";
          if(jCheckBox43.isSelected()) dom=jComboBox106.getSelectedItem()+"";
          if(jCheckBox42.isSelected()) month=(jComboBox105.getSelectedIndex()+1)+"";
          if(jCheckBox41.isSelected()) year=jComboBox104.getSelectedItem()+"";
          if(jCheckBox40.isSelected()){
          franja=new String[2];
          franja[0]=jComboBox103.getSelectedIndex()+"";
          franja[1]=jComboBox104.getSelectedIndex()+"";
          }
          if(jCheckBox39.isSelected()){
          desde=new String[3];
          desde[0]=jComboBox101.getSelectedItem()+"";
          desde[1]=jComboBox100.getSelectedIndex()+"";
          desde[2]=jComboBox98.getSelectedItem()+"";
          Hasta=new String[3];
          Hasta[0]=jComboBox94.getSelectedItem()+"";
          Hasta[1]=jComboBox95.getSelectedIndex()+"";
          Hasta[2]=jComboBox96.getSelectedItem()+"";
          }
          if(jComboBox93.getSelectedIndex()!=0) tipo_usuario=jComboBox93.getSelectedIndex()+"";
          if(AreasComboBoxPDD.getSelectedIndex()!=0) area=areasExistentes.get(AreasComboBoxPDD.getSelectedIndex()-1).getID();
          if(AutorComboBoxPDD.getSelectedIndex()!=0) autor=autoresExistentes.get(AutorComboBoxPDD.getSelectedIndex()-1).getCorreo();
          if(DocTipoComboBoxPDD.getSelectedIndex()!=0) doc_tipo=tdExistentes.get(DocTipoComboBoxPDD.getSelectedIndex()-1).getTipoDocumento();
          if(jTextField7.isCursorSet() && !jTextField7.getText().isEmpty()) usuario=jTextField7.getText();
          int salida=Integer.parseInt(Num_Doc1.getText());
          biblioteca.Main.PdfCreator.createPdf("documentosMásDescargados.pdf", "Reporte de Documentos Más Descargados", 
                  "Total de documentos en este reporte: ",new ControladorEstadisticas().estadisticasDocumentosDescargados(dow, dom, month, year, tipo_usuario,
               franja, desde,Hasta,area, autor, doc_tipo, usuario, jCheckBox45.isSelected(), salida));
    }//GEN-LAST:event_Reporte_DescargadosActionPerformed

    private void Reporte_ConsultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reporte_ConsultadosActionPerformed
        String dow = null, dom = null, month = null, year = null, tipo_usuario = null;
        String[] franja = null, desde = null, Hasta = null;
        String area = null, autor=null, doc_tipo=null, usuario=null;
      
      
      if(!jCheckBox31.isSelected()){
          if(jCheckBox32.isSelected()) dow=jComboBox76.getSelectedIndex()+"";
          if(jCheckBox33.isSelected()) dom=jComboBox77.getSelectedItem()+"";
          if(jCheckBox34.isSelected()) month=(jComboBox78.getSelectedIndex()+1)+"";
          if(jCheckBox35.isSelected()) year=jComboBox81.getSelectedItem()+"";
          if(jCheckBox36.isSelected()){
          franja=new String[2];
          franja[0]=jComboBox79.getSelectedIndex()+"";
          franja[1]=jComboBox80.getSelectedIndex()+"";
          }
          if(jCheckBox37.isSelected()){
          desde=new String[3];
          desde[0]=jComboBox82.getSelectedItem()+"";
          desde[1]=jComboBox83.getSelectedIndex()+"";
          desde[2]=jComboBox84.getSelectedItem()+"";
          Hasta=new String[3];
          Hasta[0]=jComboBox89.getSelectedItem()+"";
          Hasta[1]=jComboBox88.getSelectedIndex()+"";
          Hasta[2]=jComboBox87.getSelectedItem()+"";
          }
      }
          if(jComboBox90.getSelectedIndex()!=0) tipo_usuario=jComboBox90.getSelectedIndex()+"";
          if(AreasComboBoxPDC.getSelectedIndex()!=0) area=areasExistentes.get(AreasComboBoxPDC.getSelectedIndex()-1).getID();
          if(AutorComboBoxPDC.getSelectedIndex()!=0) autor=autoresExistentes.get(AutorComboBoxPDC.getSelectedIndex()-1).getCorreo();
          if(DocTipoComboBoxPDC.getSelectedIndex()!=0) doc_tipo=tdExistentes.get(DocTipoComboBoxPDC.getSelectedIndex()-1).getTipoDocumento();
          usuario=jTextField6.getText();
          //biblioteca.Main.PdfCreator.createPdf("documentosConsultados.pdf", "Reporte de Documentos Consultados", "Total de documentos consultados en este reporte: ", 
          //      new ControladorReportesEstadisticas().ConsultarListaDocumentosConsultados(dow, dom, month, year, tipo_usuario,
          //     franja, desde,Hasta,area, autor, doc_tipo, usuario));
    }//GEN-LAST:event_Reporte_ConsultadosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox AreasComboBoxPDC;
    private javax.swing.JComboBox AreasComboBoxPDD;
    private javax.swing.JComboBox AutorComboBoxPDC;
    private javax.swing.JComboBox AutorComboBoxPDD;
    private javax.swing.JComboBox DocTipoComboBoxPDC;
    private javax.swing.JComboBox DocTipoComboBoxPDD;
    private javax.swing.JTextField Num_Doc;
    private javax.swing.JTextField Num_Doc1;
    private javax.swing.JPanel Panel_Documentos_Catalogados1;
    private javax.swing.JButton Reporte_Consultados;
    private javax.swing.JButton Reporte_Descargados;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox32;
    private javax.swing.JCheckBox jCheckBox33;
    private javax.swing.JCheckBox jCheckBox34;
    private javax.swing.JCheckBox jCheckBox35;
    private javax.swing.JCheckBox jCheckBox36;
    private javax.swing.JCheckBox jCheckBox37;
    private javax.swing.JCheckBox jCheckBox39;
    private javax.swing.JCheckBox jCheckBox40;
    private javax.swing.JCheckBox jCheckBox41;
    private javax.swing.JCheckBox jCheckBox42;
    private javax.swing.JCheckBox jCheckBox43;
    private javax.swing.JCheckBox jCheckBox44;
    private javax.swing.JCheckBox jCheckBox45;
    private javax.swing.JComboBox jComboBox100;
    private javax.swing.JComboBox jComboBox101;
    private javax.swing.JComboBox jComboBox102;
    private javax.swing.JComboBox jComboBox103;
    private javax.swing.JComboBox jComboBox104;
    private javax.swing.JComboBox jComboBox105;
    private javax.swing.JComboBox jComboBox106;
    private javax.swing.JComboBox jComboBox107;
    private javax.swing.JComboBox jComboBox76;
    private javax.swing.JComboBox jComboBox77;
    private javax.swing.JComboBox jComboBox78;
    private javax.swing.JComboBox jComboBox79;
    private javax.swing.JComboBox jComboBox80;
    private javax.swing.JComboBox jComboBox81;
    private javax.swing.JComboBox jComboBox82;
    private javax.swing.JComboBox jComboBox83;
    private javax.swing.JComboBox jComboBox84;
    private javax.swing.JComboBox jComboBox87;
    private javax.swing.JComboBox jComboBox88;
    private javax.swing.JComboBox jComboBox89;
    private javax.swing.JComboBox jComboBox90;
    private javax.swing.JComboBox jComboBox93;
    private javax.swing.JComboBox jComboBox94;
    private javax.swing.JComboBox jComboBox95;
    private javax.swing.JComboBox jComboBox96;
    private javax.swing.JComboBox jComboBox98;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
